
from alembic import op
import sqlalchemy as sa


revision = '2afd5fa8f4a2'
down_revision = 'b256d59ca313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackable_types', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('trackable_types_name_key'), 'trackable_types', type_='unique')
    op.create_foreign_key(None, 'trackable_types', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackable_types', type_='foreignkey')
    op.create_unique_constraint(op.f('trackable_types_name_key'), 'trackable_types', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('trackable_types', 'user_id')
    # ### end Alembic commands ###
