
from alembic import op
import sqlalchemy as sa


revision = 'b814cecbec68'
down_revision = '706c352a118c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('countries_code_key'), 'countries', type_='unique')
    op.drop_constraint(op.f('countries_name_key'), 'countries', type_='unique')
    op.create_unique_constraint(op.f('uq_countries_code'), 'countries', ['code'])
    op.create_unique_constraint(op.f('uq_countries_name'), 'countries', ['name'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_countries_name'), 'countries', type_='unique')
    op.drop_constraint(op.f('uq_countries_code'), 'countries', type_='unique')
    op.create_unique_constraint(op.f('countries_name_key'), 'countries', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('countries_code_key'), 'countries', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
