services:
  celery-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.celery
    container_name: celery-worker
    restart: always
    environment:
      ENVIRONMENT: production
      GCP_CREDENTIALS_PATH: /app/secrets/service-account.json
    volumes:
      - ../secrets/google/service-account.json:/app/secrets/service-account.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
